import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home() {
  const [api, setApi] = useState();

  useEffect(() => {
    axios.get("http://127.0.0.1:3333/").then((res) => {
      setApi(res.data.hello);
      console.log(api);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          test <a>{api}</a>
        </h1>
      </main>
    </div>
  );
}
